source 'https://rubygems.org'

gem 'cucumber',    '~>1.3'
gem 'capybara',    '~>2.4'
gem 'poltergeist', '~>1.5'
gem 'pry',         '~>0.10'
gem 'sinatra',     '~>1.4'
gem 'launchy',     '~>2.4'
gem 'rspec',       '~>3.0'
gem 'redcarpet',   '~>3.1'
