source 'https://rubygems.org'

gem 'rdiscount',   '~> 2.1.7'
gem 'haml',        '~> 4.0'
gem 'cucumber',    '~> 1.3'
gem 'capybara',    '~> 2.4'
gem 'poltergeist', '~> 1.5'
gem 'pry',         '~> 0.10'
gem 'sinatra',     '~> 1.4'
gem 'launchy',     '~> 2.4'
gem 'rspec',       '~> 3.0'
gem 'redcarpet',   '~> 3.1'
gem 'eval_in',     '~> 0.1.6'
gem 'webmock',     '~> 1.18'
